apiVersion: v1
kind: Service
metadata: #Dictinoary
  name: loadbalanacer-service
spec: #Dictinoary
  type: LoadBalancer
  selector:
    app: myapp
  ports: #List
    - name: http
      port: 80
      targetPort: 80