apiVersion: v1
kind: ConfigMap
metadata:
  name: acc-spec-config
  namespace: {{ .values.namespace}}
  labels:
    app: acc-spec
data:
  POSTGRES_HOST:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  POSTGRES_DB:
  PORT:
  SERVER_PORT: