apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: acc-spec
  namespace: {{ }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acc-spec
  minReplicas: {{ }}
  maxReplicas: {{ }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: {{ }}
    - type: Resource
      resource:
        name: memory
        target: 
          type: AverageValue
          averageValue: {{ }}
