apiVersion: v1
kind: Service
metadata:
  name: acc-spec
  namespace: {{ .values.namespace }}
  labels:
    app: acc-spec
spec:
  type: ClusterIp
  selector:
    app: acc-spec
  ports:
  - protocol: TCP
    port: 
    targetport: