---
- hosts: all
  become: true

  tasks:
    - name: stop ubuntu servers only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == 'Debian'
        
        