apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  labels:
    app: html-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
        tier: frontend
    spec:
      containers:
        - name: html-app
          image: bhanuprakash2710/htmlpage:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
  labels:
    app: html-app
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: html-app
  ports:
    - name: http
      port: 80
      targetPort: 80
