---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-ec2-instance"
    #key_name: "prod-ssh-key"
    #vpc_subnet_id: subnet-5ca1ab1e
    instance_type: t2.micro
    security_group: default
    region: ap-south-1
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    network_interfaces:
      - assign_public_ip: true
    image_id: ami-0861f4e788f5069dd


    